# Generated by Django 6.0 on 2026-02-07 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('responsible_document', models.CharField(blank=True, help_text='RUC (11 dígitos) o DNI (8 dígitos) del responsable', max_length=11, null=True, verbose_name='RUC o DNI del Responsable')),
                ('responsible_names', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres del Responsable')),
                ('responsible_last_names', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos del Responsable')),
                ('ruc', models.CharField(blank=True, help_text='RUC de la empresa (11 dígitos)', max_length=11, null=True, unique=True, verbose_name='RUC')),
                ('legal_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social')),
                ('commercial_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Comercial')),
                ('fiscal_address', models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada GPS de la empresa', max_digits=10, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada GPS de la empresa', max_digits=10, null=True, verbose_name='Longitud')),
                ('email', models.EmailField(blank=True, help_text='Correo para login de empresa', max_length=100, null=True, unique=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='Logo')),
                ('password', models.CharField(blank=True, help_text='Contraseña hasheada para login de empresa', max_length=128, null=True, verbose_name='Contraseña')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['legal_name'],
                'indexes': [models.Index(fields=['ruc'], name='companies_c_ruc_68064a_idx'), models.Index(fields=['email'], name='companies_c_email_aa1293_idx'), models.Index(fields=['is_active'], name='companies_c_is_acti_03043b_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ej: Diario, Semanal, Mensual', max_length=50, verbose_name='Nombre')),
                ('periodicity', models.CharField(choices=[('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quincenal'), ('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('CUSTOM', 'Personalizado')], default='DAILY', help_text='Frecuencia de los pagos (diario, semanal, mensual)', max_length=20, verbose_name='Periodicidad')),
                ('default_interest_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tasa de interés por defecto en porcentaje (ej: 8.00 para 8%)', max_digits=5, verbose_name='Tasa de Interés (%)')),
                ('suggested_installments', models.IntegerField(default=1, help_text='Número de cuotas sugerido para este tipo de préstamo', verbose_name='Cuotas Sugeridas')),
                ('description', models.TextField(blank=True, help_text='Descripción del tipo de préstamo', null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Empresa a la que pertenece este tipo de préstamo', on_delete=django.db.models.deletion.CASCADE, related_name='loan_types', to='companies.company')),
            ],
            options={
                'verbose_name': 'Tipo de Préstamo',
                'verbose_name_plural': 'Tipos de Préstamo',
                'ordering': ['company', 'name'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='companies_l_company_aada7f_idx')],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
