# Generated by Django 6.0 on 2026-02-07 03:52

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto del pago aplicado a esta cuota', max_digits=15, verbose_name='Monto Aplicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pago-Cuota',
                'verbose_name_plural': 'Pagos-Cuotas',
            },
        ),
        migrations.CreateModel(
            name='PenaltyAdjustment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('REDUCE', 'Reducir'), ('ELIMINATE', 'Eliminar'), ('MODIFY', 'Modificar')], help_text='Tipo de ajuste: Reducir, Eliminar o Modificar', max_length=20, verbose_name='Tipo de Ajuste')),
                ('previous_penalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de mora antes del ajuste', max_digits=15, verbose_name='Mora Anterior')),
                ('new_penalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de mora después del ajuste', max_digits=15, verbose_name='Mora Nueva')),
                ('reason', models.TextField(help_text='Motivo del ajuste de mora', verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ajuste de Mora',
                'verbose_name_plural': 'Ajustes de Mora',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto pagado en soles (PEN)', max_digits=15, verbose_name='Monto')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora del pago', verbose_name='Fecha de Pago')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('BCP', 'BCP'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('TRANSFER', 'Transferencia')], default='CASH', help_text='Método de pago utilizado', max_length=20, verbose_name='Método de Pago')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='COMPLETED', help_text='Estado del pago', max_length=20, verbose_name='Estado')),
                ('reference_number', models.CharField(blank=True, help_text='Número de referencia del pago (operación, voucher, etc.)', max_length=100, null=True, verbose_name='Número de Referencia')),
                ('observations', models.TextField(blank=True, help_text='Observaciones adicionales sobre el pago', null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Cliente que realiza el pago', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.client')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-payment_date'],
            },
        ),
    ]
