# Generated by Django 6.0 on 2026-02-07 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('loans', '0002_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='collector',
            field=models.ForeignKey(blank=True, help_text='Cobrador que registró el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(help_text='Empresa que recibe el pago', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='companies.company'),
        ),
        migrations.AddField(
            model_name='payment',
            name='loan',
            field=models.ForeignKey(help_text='Préstamo al que se aplica el pago', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='installment',
            field=models.ForeignKey(help_text='Cuota cubierta por este pago', on_delete=django.db.models.deletion.CASCADE, related_name='payment_installments', to='loans.installment'),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='payment',
            field=models.ForeignKey(help_text='Pago que cubre esta cuota', on_delete=django.db.models.deletion.CASCADE, related_name='payment_installments', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='penaltyadjustment',
            name='adjusted_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó el ajuste', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalty_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penaltyadjustment',
            name='loan',
            field=models.ForeignKey(help_text='Préstamo al que se aplica el ajuste de mora', on_delete=django.db.models.deletion.CASCADE, related_name='penalty_adjustments', to='loans.loan'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'client', 'payment_date'], name='payments_pa_company_c6c9b0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['loan', 'status'], name='payments_pa_loan_id_4c6d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['collector', 'payment_date'], name='payments_pa_collect_824f14_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method', 'payment_date'], name='payments_pa_payment_97fe28_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinstallment',
            index=models.Index(fields=['payment', 'installment'], name='payments_pa_payment_b1c65f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentinstallment',
            unique_together={('payment', 'installment')},
        ),
        migrations.AddIndex(
            model_name='penaltyadjustment',
            index=models.Index(fields=['loan', 'created_at'], name='payments_pe_loan_id_545803_idx'),
        ),
        migrations.AddIndex(
            model_name='penaltyadjustment',
            index=models.Index(fields=['adjusted_by', 'created_at'], name='payments_pe_adjuste_1d4903_idx'),
        ),
    ]
