# Generated by Django 6.0 on 2026-02-07 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('companies', '0001_initial'),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('dni', models.CharField(help_text='DNI del usuario (8 dígitos) - usado para login', max_length=8, unique=True, verbose_name='DNI')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono/Celular')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('COLLECTOR', 'Cobrador')], default='COLLECTOR', help_text='Rol del usuario: Administrador o Cobrador', max_length=20, verbose_name='Cargo')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/', verbose_name='Foto')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Apellidos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Es Superusuario')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('company', models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='companies.company')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('zones', models.ManyToManyField(blank=True, help_text='Zonas asignadas al cobrador', related_name='collectors', to='zones.zone')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['dni'], name='users_user_dni_287748_idx'), models.Index(fields=['email'], name='users_user_email_6f2530_idx'), models.Index(fields=['company', 'role'], name='users_user_company_9b5f6c_idx'), models.Index(fields=['is_active'], name='users_user_is_acti_ddda02_idx')],
            },
        ),
    ]
