# Generated by Django 6.0 on 2026-02-07 03:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('installment_number', models.IntegerField(help_text='Número de la cuota (1, 2, 3, ...)', verbose_name='Número de Cuota')),
                ('due_date', models.DateField(help_text='Fecha de vencimiento de la cuota', verbose_name='Fecha de Vencimiento')),
                ('capital_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de capital de esta cuota', max_digits=15, verbose_name='Capital')),
                ('interest_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de interés de esta cuota', max_digits=15, verbose_name='Interés')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total de la cuota (capital + interés)', max_digits=15, verbose_name='Total')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto pagado de esta cuota', max_digits=15, verbose_name='Monto Pagado')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagada'), ('OVERDUE', 'Vencida'), ('PARTIALLY_PAID', 'Parcialmente Pagada'), ('CANCELLED', 'Cancelada')], default='PENDING', help_text='Estado actual de la cuota', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['loan', 'installment_number'],
            },
        ),
        migrations.CreateModel(
            name='Refinancing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo pendiente del préstamo original al refinanciar', max_digits=15, verbose_name='Saldo Pendiente')),
                ('refinanced_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto del nuevo préstamo refinanciado', max_digits=15, verbose_name='Monto Refinanciado')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tasa de interés aplicada en el refinanciamiento', max_digits=5, verbose_name='Tasa de Interés (%)')),
                ('new_period_days', models.IntegerField(help_text='Nuevo plazo del préstamo refinanciado en días', verbose_name='Nuevo Plazo (Días)')),
                ('reason', models.TextField(blank=True, help_text='Motivo del refinanciamiento', null=True, verbose_name='Motivo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('CANCELLED', 'Cancelado')], default='PENDING', help_text='Estado del refinanciamiento', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Refinanciamiento',
                'verbose_name_plural': 'Refinanciamientos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('initial_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto inicial del préstamo en soles (PEN)', max_digits=15, verbose_name='Monto Inicial')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tasa de interés en porcentaje (ej: 8.00 para 8%)', max_digits=5, verbose_name='Tasa de Interés (%)')),
                ('number_of_installments', models.IntegerField(default=1, help_text='Número total de cuotas del préstamo', verbose_name='Número de Cuotas')),
                ('periodicity', models.CharField(choices=[('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quincenal'), ('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('CUSTOM', 'Personalizado')], default='DAILY', help_text='Frecuencia de pago de las cuotas', max_length=20, verbose_name='Periodicidad')),
                ('start_date', models.DateField(help_text='Fecha de inicio del préstamo', verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(help_text='Fecha final de vencimiento del préstamo', verbose_name='Fecha de Vencimiento')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total a pagar (capital + intereses)', max_digits=15, verbose_name='Monto Total')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total pagado hasta el momento', max_digits=15, verbose_name='Monto Pagado')),
                ('pending_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo pendiente por pagar', max_digits=15, verbose_name='Saldo Pendiente')),
                ('penalty_type', models.CharField(blank=True, choices=[('FIXED', 'Fija'), ('PERCENTAGE', 'Porcentual')], help_text='Tipo de mora: Fija o Porcentual', max_length=20, null=True, verbose_name='Tipo de Mora')),
                ('penalty_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Monto fijo de mora (si aplica)', max_digits=15, null=True, verbose_name='Monto de Mora Fija')),
                ('penalty_percentage', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de mora por día (si aplica)', max_digits=5, null=True, verbose_name='Porcentaje de Mora')),
                ('penalty_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Mora total aplicada hasta el momento', max_digits=15, verbose_name='Mora Aplicada')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('COMPLETED', 'Completado'), ('DEFAULTING', 'Moroso'), ('REFINANCED', 'Refinanciado'), ('CANCELLED', 'Cancelado')], default='ACTIVE', help_text='Estado actual del préstamo', max_length=20, verbose_name='Estado')),
                ('observations', models.TextField(blank=True, help_text='Observaciones adicionales sobre el préstamo', null=True, verbose_name='Observaciones')),
                ('is_refinanced', models.BooleanField(default=False, help_text='Indica si este préstamo es resultado de un refinanciamiento', verbose_name='Es Refinanciado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Cliente que recibe el préstamo', on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='clients.client')),
                ('company', models.ForeignKey(help_text='Empresa que otorga el préstamo', on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='companies.company')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-created_at'],
            },
        ),
    ]
