# Generated by Django 6.0 on 2026-02-07 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el préstamo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.ForeignKey(blank=True, help_text='Tipo de préstamo de referencia (puede ser modificado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='companies.loantype'),
        ),
        migrations.AddField(
            model_name='loan',
            name='original_loan',
            field=models.ForeignKey(blank=True, help_text='Préstamo original si este es un refinanciamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refinanced_loans', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='installment',
            name='loan',
            field=models.ForeignKey(help_text='Préstamo al que pertenece esta cuota', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='refinancing',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el refinanciamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_refinancings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refinancing',
            name='new_loan',
            field=models.OneToOneField(blank=True, help_text='Nuevo préstamo creado por el refinanciamiento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refinancing', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='refinancing',
            name='original_loan',
            field=models.ForeignKey(help_text='Préstamo original que se refinancia', on_delete=django.db.models.deletion.CASCADE, related_name='refinancings', to='loans.loan'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['company', 'client', 'status'], name='loans_loan_company_d966cb_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status', 'end_date'], name='loans_loan_status_09d1cd_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['client', 'status'], name='loans_loan_client__a27993_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['original_loan'], name='loans_loan_origina_6e67d7_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['loan', 'status'], name='loans_insta_loan_id_1d25e0_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['due_date', 'status'], name='loans_insta_due_dat_355a79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('loan', 'installment_number')},
        ),
        migrations.AddIndex(
            model_name='refinancing',
            index=models.Index(fields=['original_loan', 'status'], name='loans_refin_origina_7fa657_idx'),
        ),
        migrations.AddIndex(
            model_name='refinancing',
            index=models.Index(fields=['status'], name='loans_refin_status_069958_idx'),
        ),
    ]
