# Generated by Django 6.0 on 2026-02-07 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(help_text='DNI del cliente (8 dígitos)', max_length=8, unique=True, verbose_name='DNI')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo')),
                ('home_address', models.TextField(blank=True, null=True, verbose_name='Dirección Domicilio')),
                ('business_address', models.TextField(blank=True, null=True, verbose_name='Dirección Negocio')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada GPS del negocio o domicilio', max_digits=10, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada GPS del negocio o domicilio', max_digits=10, null=True, verbose_name='Longitud')),
                ('classification', models.CharField(choices=[('PUNCTUAL', 'Puntual'), ('REGULAR', 'Regular'), ('DEFAULTING', 'Moroso'), ('SEVERELY_DEFAULTING', 'Muy Moroso')], default='REGULAR', help_text='Clasificación según historial de pagos', max_length=30, verbose_name='Clasificación')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el cliente', null=True, verbose_name='Observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Empresa a la que pertenece este cliente', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='companies.company')),
                ('zone', models.ForeignKey(blank=True, help_text='Zona asignada al cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='zones.zone')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('DNI', 'Foto de DNI'), ('RECEIPT', 'Recibo (Agua/Luz)'), ('ADDITIONAL', 'Foto Adicional'), ('CONTRACT', 'Contrato'), ('OTHER', 'Otro')], default='DNI', help_text='Tipo de documento (DNI, Recibo, etc.)', max_length=20, verbose_name='Tipo de Documento')),
                ('file', models.FileField(help_text='Archivo del documento (DNI, recibo agua/luz, etc.)', upload_to='clients/documents/', verbose_name='Archivo')),
                ('description', models.TextField(blank=True, help_text='Descripción o notas del documento', null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Cliente al que pertenece este documento', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client')),
            ],
            options={
                'verbose_name': 'Documento de Cliente',
                'verbose_name_plural': 'Documentos de Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['dni'], name='clients_cli_dni_fca805_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company', 'zone'], name='clients_cli_company_887ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['classification'], name='clients_cli_classif_bca313_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active'], name='clients_cli_is_acti_57c1e7_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['client', 'document_type'], name='clients_cli_client__f10a65_idx'),
        ),
    ]
