# Generated by Django 6.0 on 2026-02-07 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre de la zona (ej: Zona Norte, Centro, Sur)', max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Descripción de la zona y sus características', null=True, verbose_name='Descripción')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada GPS central de la zona', max_digits=10, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada GPS central de la zona', max_digits=10, null=True, verbose_name='Longitud')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('INACTIVE', 'Inactiva')], default='ACTIVE', help_text='Estado de la zona (Activa/Inactiva)', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Empresa a la que pertenece esta zona', on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='companies.company')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['company', 'name'],
                'indexes': [models.Index(fields=['company', 'status'], name='zones_zone_company_34c5f6_idx')],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
